"use client";

import React, { useState } from "react";
import { TodoCategory } from "@/features/categories/types/category";
import { useCategories } from "@/features/categories/hooks/useCategories";

interface CategoryFormProps {
  category: TodoCategory | null; // null = create mode, TodoCategory = edit mode
  onClose: () => void;
}

export default function CategoryForm({ category, onClose }: CategoryFormProps) {
  const { createCategory, updateCategory } = useCategories();
  const [categoryName, setCategoryName] = useState(category?.categoryName ?? "");
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);

    const trimmedName = categoryName.trim();
    if (!trimmedName) {
      setError("Category name is required.");
      return;
    }
    if (trimmedName.length > 128) {
      setError("Category name must be 128 characters or fewer.");
      return;
    }

    setSubmitting(true);
    try {
      if (category) {
        // Edit mode: pass full updated entity (2-arg form per CategoryProvider)
        await updateCategory(category.id, { ...category, categoryName: trimmedName });
      } else {
        // Create mode: UUID is generated by CategoryProvider
        await createCategory({ categoryName: trimmedName, categorySort: 0, tag: null });
      }
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save category");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={(e) => void handleSubmit(e)} className="flex flex-col gap-4">
      <div>
        <label
          htmlFor="category-name"
          className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
        >
          Category name <span aria-hidden="true">*</span>
        </label>
        <input
          id="category-name"
          type="text"
          value={categoryName}
          maxLength={128}
          onChange={(e) => setCategoryName(e.target.value)}
          required
          autoFocus
          placeholder="e.g. Work, Personal"
          className="w-full rounded border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>
      {error && (
        <p role="alert" className="text-sm text-red-600 dark:text-red-400">
          {error}
        </p>
      )}
      <div className="flex gap-3 justify-end pt-2">
        <button
          type="button"
          onClick={onClose}
          disabled={submitting}
          className="rounded px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={submitting}
          className="rounded px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 disabled:opacity-50"
        >
          {submitting ? "Saving\u2026" : category ? "Save" : "Create"}
        </button>
      </div>
    </form>
  );
}
