"use client";

import React, { useState } from "react";
import { TodoPriority } from "@/features/priorities/types/priority";
import { usePriorities } from "@/features/priorities/hooks/usePriorities";

interface PriorityFormProps {
  priority: TodoPriority | null; // null = create mode, TodoPriority = edit mode
  onClose: () => void;
}

export default function PriorityForm({ priority, onClose }: PriorityFormProps) {
  const { createPriority, updatePriority } = usePriorities();
  const [priorityName, setPriorityName] = useState(priority?.priorityName ?? "");
  const [error, setError] = useState<string | null>(null);
  const [submitting, setSubmitting] = useState(false);

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    setError(null);

    const trimmedName = priorityName.trim();
    if (!trimmedName) {
      setError("Priority name is required.");
      return;
    }
    if (trimmedName.length > 128) {
      setError("Priority name must be 128 characters or fewer.");
      return;
    }

    setSubmitting(true);
    try {
      if (priority) {
        // Edit mode: pass full updated entity (2-arg form per PriorityProvider)
        await updatePriority(priority.id, { ...priority, priorityName: trimmedName });
      } else {
        // Create mode: UUID is generated by PriorityProvider
        await createPriority({ priorityName: trimmedName, prioritySort: 0, tag: null });
      }
      onClose();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to save priority");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <form onSubmit={(e) => void handleSubmit(e)} className="flex flex-col gap-4">
      <div>
        <label
          htmlFor="priority-name"
          className="block text-sm font-medium text-gray-700 dark:text-gray-300 mb-1"
        >
          Priority name <span aria-hidden="true">*</span>
        </label>
        <input
          id="priority-name"
          type="text"
          value={priorityName}
          maxLength={128}
          onChange={(e) => setPriorityName(e.target.value)}
          required
          autoFocus
          placeholder="e.g. High, Medium, Low"
          className="w-full rounded border border-gray-300 dark:border-gray-600 px-3 py-2 text-sm bg-white dark:bg-gray-700 text-gray-900 dark:text-gray-100 focus:outline-none focus:ring-2 focus:ring-blue-500"
        />
      </div>
      {error && (
        <p role="alert" className="text-sm text-red-600 dark:text-red-400">
          {error}
        </p>
      )}
      <div className="flex gap-3 justify-end pt-2">
        <button
          type="button"
          onClick={onClose}
          disabled={submitting}
          className="rounded px-4 py-2 text-sm font-medium text-gray-700 dark:text-gray-300 hover:bg-gray-100 dark:hover:bg-gray-700"
        >
          Cancel
        </button>
        <button
          type="submit"
          disabled={submitting}
          className="rounded px-4 py-2 text-sm font-medium text-white bg-blue-600 hover:bg-blue-700 disabled:opacity-50"
        >
          {submitting ? "Saving\u2026" : priority ? "Save" : "Create"}
        </button>
      </div>
    </form>
  );
}
